-- 코드를 입력하세요
SELECT A.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS, ROUND(AVG(REVIEW_SCORE),2)AS SCORE
FROM REST_INFO A right join REST_REVIEW B
ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
group by A.REST_ID
order by SCORE desc, FAVORITES DESC