-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK A JOIN AUTHOR B USING (AUTHOR_ID)
WHERE CATEGORY = '경제' and A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY PUBLISHED_DATE